// Currency options for selector components with values and labels
const currencyOptions = [
    {value:'USD', label:'USD US dollar'},
    {value:'EUR', label:'EUR Euro'},
    {value:'AED', label:'AED United Arab Emirates dirham'},
    {value:'AFN', label:'AFN Afghan afghani'},
    {value:'ALL', label:'ALL Albanian lek'},
    {value:'AMD', label:'AMD Armenian dram'},
    {value:'ANG', label:'ANG Angolan guilder'},
    {value:'AOA', label:'AOA Angolan kwanza'},
    {value:'ARS', label:'ARS Argentine peso'},
    {value:'AUD', label:'AUD Australian dollar'},
    {value:'AWG', label:'AWG Aruban florin'},
    {value:'AZN', label:'AZN Azerbaijani manat'},
    {value:'BAM', label:'BAM Bosnia and Herzegovina convertible mark'},
    {value:'BBD', label:'BBD Barbados dollar'},
    {value:'BDT', label:'BDT Bangladeshi taka'},
    {value:'BGN', label:'BGN Bulgarian lev'},
    {value:'BHD', label:'BHD Bahraini dinar'},
    {value:'BIF', label:'BIF Burundian franc'},
    {value:'BMD', label:'BMD Bermudian dollar'},
    {value:'BND', label:'BND Brunei dollar'},
    {value:'BOB', label:'BOB Bolivia boliviano'},
    {value:'BRL', label:'BRL Brazilian real'},
    {value:'BSD', label:'BSD Bahamian dollar'},
    {value:'BTN', label:'BTN Bhutanese ngultrum'},
    {value:'BWP', label:'BWP Botswana pula'},
    {value:'BYN', label:'BYN Belarusian ruble'},
    {value:'BZD', label:'BZD Belize dollar'},
    {value:'CAD', label:'CAD Canadian dollar'},
    {value:'CDF', label:'CDF Congolese franc'},
    {value:'CHF', label:'CHF Swiss franc'},
    {value:'CLP', label:'CLP Chilean peso'},
    {value:'CNY', label:'CNY Chinese yuan'},
    {value:'COP', label:'COP Colombian peso'},
    {value:'CRC', label:'CRC Costa Rican colon'},
    {value:'CUC', label:'CUC Cuban convertible peso'},
    {value:'CUP', label:'CUP Cuban peso'},
    {value:'CVE', label:'CVE Cape Verdean escudo'},
    {value:'CZK', label:'CZK Czech koruna'},
    {value:'DJF', label:'DJF Djiboutian franc'},
    {value:'DKK', label:'DKK Danish krone'},
    {value:'DOP', label:'DOP Dominican peso'},
    {value:'DZD', label:'DZD Algerian dinar'},
    {value:'EGP', label:'EGP Egyptian pound'},
    {value:'ERN', label:'ERN Eritrean nakfa'},
    {value:'ETB', label:'ETB Ethiopian birr'},
    {value:'FJD', label:'FJD Fiji dollar'},
    {value:'FKP', label:'FKP Falkland Islands pound'},
    {value:'GBP', label:'GBP British pound'},
    {value:'GEL', label:'GEL Georgian lari'},
    {value:'GHS', label:'GHS Ghanaian cedi'},
    {value: "GIP", label: "GIP Gibraltar Pound" },
    { value: "GMD", label: "GMD Gambian Dalasi" },
    { value: "GNF", label: "GNF Guinean Franc" },
    { value: "GTQ", label: "GTQ Guatemalan Quetzal" },
    { value: "GYD", label: "GYD Guyanese Dollar" },
    { value: "HKD", label: "HKD Hong Kong Dollar" },
    { value: "HNL", label: "HNL Honduran Lempira" },
    { value: "HRK", label: "HRK Croatian Kuna" },
    { value: "HTG", label: "HTG Haitian Gourde" },
    { value: "HUF", label: "HUF Hungarian Forint" },
    { value: "IDR", label: "IDR Indonesian Rupiah" },
    { value: "ILS", label: "ILS Israeli Shekel" },
    { value: "IMP", label: "IMP Isle of Man Pound" },
    { value: "INR", label: "INR Indian Rupee" },
    { value: "IQD", label: "IQD Iraqi Dinar" },
    { value: "IRR", label: "IRR Iranian Rial" },
    { value: "ISK", label: "ISK Icelandic Krona" },
    { value: "JEP", label: "JEP Jersey Pound" },
    { value: "JMD", label: "JMD Jamaican Dollar" },
    { value: "JOD", label: "JOD Jordanian Dinar" },
    { value: "JPY", label: "JPY Japanese Yen" },
    { value: "KES", label: "KES Kenyan Shilling" },
    { value: "KGS", label: "KGS Kyrgyzstani Som" },
    { value: "KHR", label: "KHR Cambodian Riel" },
    { value: "KID", label: "KID Kiribati Dollar" },
    { value: "KMF", label: "KMF Comorian Franc" },
    { value: "KRW", label: "KRW South Korean Won" },
    { value: "KWD", label: "KWD Kuwaiti Dinar" },
    { value: "KYD", label: "KYD Cayman Islands Dollar" },
    { value: "KZT", label: "KZT Kazakhstani Tenge" },
    { value: "LAK", label: "LAK Lao Kip" },
    { value: "LBP", label: "LBP Lebanese Pound" },
    { value: "LKR", label: "LKR Sri Lankan Rupee" },
    { value: "LRD", label: "LRD Liberian Dollar" },
    { value: "LSL", label: "LSL Lesotho Loti" },
    { value: "LYD", label: "LYD Libyan Dinar" },
    { value: "MAD", label: "MAD Moroccan Dirham" },
    { value: "MDL", label: "MDL Moldovan Leu" },
    { value: "MGA", label: "MGA Malagasy Ariary" },
    { value: "MKD", label: "MKD Macedonian Denar" },
    { value: "MMK", label: "MMK Myanmar Kyat" },
    { value: "MNT", label: "MNT Mongolian Tugrik" },
    { value: "MOP", label: "MOP Macanese Pataca" },
    { value: "MRU", label: "MRU Mauritanian Ouguiya" },
    { value: "MUR", label: "MUR Mauritian Rupee" },
    { value: "MVR", label: "MVR Maldivian Rufiyaa" },
    { value: "MWK", label: "MWK Malawian Kwacha" },
    { value: "MXN", label: "MXN Mexican Peso" },
    { value: "MYR", label: "MYR Malaysian Ringgit" },
    { value: "MZN", label: "MZN Mozambican Metical" },
    { value: "NAD", label: "NAD Namibian Dollar" },
    { value: "NGN", label: "NGN Nigerian Naira" },
    { value: "NIO", label: "NIO Nicaraguan Cordoba" },
    { value: "NOK", label: "NOK Norwegian Krone" },
    { value: "NPR", label: "NPR Nepalese Rupee" },
    { value: "NZD", label: "NZD New Zealand Dollar" },
    { value: "OMR", label: "OMR Omani Rial" },
    { value: "PAB", label: "PAB Panamanian Balboa" },
    { value: "PEN", label: "PEN Peruvian Sol" },
    { value: "PGK", label: "PGK Papua New Guinean Kina" },
    { value: "PHP", label: "PHP Philippine Peso" },
    { value: "PKR", label: "PKR Pakistani Rupee" },
    { value: "PLN", label: "PLN Polish Zloty" },
    { value: "PYG", label: "PYG Paraguayan Guarani" },
    { value: "QAR", label: "QAR Qatari Riyal" },
    { value: "RON", label: "RON Romanian Leu" },
    { value: "RSD", label: "RSD Serbian Dinar" },
    { value: "RUB", label: "RUB Russian Ruble" },
    { value: "RWF", label: "RWF Rwandan Franc" },
    { value: "SAR", label: "SAR Saudi Riyal" },
    { value: "SBD", label: "SBD Solomon Islands Dollar" },
    { value: "SCR", label: "SCR Seychellois Rupee" },
    { value: "SDG", label: "SDG Sudanese Pound" },
    { value: "SEK", label: "SEK Swedish Krona" },
    { value: "SGD", label: "SGD Singapore Dollar" },
    { value: "SHP", label: "SHP Saint Helena Pound" },
    { value: "SLE", label: "SLE Sierra Leonean Leone" },
    { value: "SLL", label: "SLL Sierra Leonean Leone" },
    { value: "SOS", label: "SOS Somali Shilling" },
    { value: "SRD", label: "SRD Surinamese Dollar" },
    { value: "SSP", label: "SSP South Sudanese Pound" },
    { value: "STN", label: "STN São Tomé and Príncipe Dobra" },
    { value: "SYP", label: "SYP Syrian Pound" },
    { value: "SZL", label: "SZL Swazi Lilangeni" },
    { value: "THB", label: "THB Thai Baht" },
    { value: "TJS", label: "TJS Tajikistani Somoni" },
    { value: "TMT", label: "TMT Turkmenistani Manat" },
    { value: "TND", label: "TND Tunisian Dinar" },
    { value: "TOP", label: "TOP Tongan Paʻanga" },
    { value: "TRY", label: "TRY Turkish Lira" },
    { value: "TTD", label: "TTD Trinidad and Tobago Dollar" },
    { value: "TVD", label: "TVD Tuvaluan Dollar" },
    { value: "TWD", label: "TWD New Taiwan Dollar" },
    { value: "TZS", label: "TZS Tanzanian Shilling" },
    { value: "UAH", label: "UAH Ukrainian Hryvnia" },
    { value: "UGX", label: "UGX Ugandan Shilling" },
    { value: "UYU", label: "UYU Uruguayan Peso" },
    { value: "UZS", label: "UZS Uzbekistani Som" },
    { value: "VES", label: "VES Venezuelan Bolívar" },
    { value: "VND", label: "VND Vietnamese Dong" },
    { value: "VUV", label: "VUV Vanuatu Vatu" },
    { value: "WST", label: "WST Samoan Tala" },
    { value: "XAF", label: "XAF Central African CFA Franc" },
    { value: "XCD", label: "XCD East Caribbean Dollar" },
    { value: "XDR", label: "XDR Special Drawing Rights" },
    { value: "XOF", label: "XOF West African CFA Franc" },
    { value: "XPF", label: "XPF CFP Franc" },
    { value: "YER", label: "YER Yemeni Rial" },
    { value: "ZAR", label: "ZAR South African Rand" },
    { value: "ZMW", label: "ZMW Zambian Kwacha" },
    { value: "ZWL", label: "ZWL Zimbabwean Dollar" }
]

export default currencyOptions